// Curated icon set offered in the icon picker (Edit tracker + Create tracker).
// Strings must match Lucide component names exactly. Stable: renaming would
// orphan any tracker whose `icon` value points at the old name.
export const ICON_OPTIONS = [
  'Box',
  'CircleDot',
  'Star',
  'Heart',
  'Bookmark',
  'Target',
  'Home',
  'ListChecks',
  'Briefcase',
  'Calendar',
  'Clock',
  'Wallet',
  'UtensilsCrossed',
  'Coffee',
  'Apple',
  'Pill',
  'Moon',
  'Droplet',
  'Dumbbell',
  'Music',
  'Book',
  'Film',
  'ShoppingBag',
  'Gift',
  'Camera',
  'Plane',
  'PawPrint',
  'Leaf',
  'Scale',
  'Donut',
];
