// The icon picker's set, for both Edit tracker and Create tracker. Strings must
// match Lucide component names exactly, and renaming one orphans any tracker
// pointing at the old name.
export const ICON_OPTIONS = [
  'Box',
  'CircleDot',
  'Star',
  'Heart',
  'Bookmark',
  'Target',
  'Home',
  'ListChecks',
  'Briefcase',
  'Calendar',
  'Clock',
  'Wallet',
  'UtensilsCrossed',
  'Coffee',
  'Apple',
  'Pill',
  'Moon',
  'Droplet',
  'Dumbbell',
  'Music',
  'Book',
  'Film',
  'ShoppingBag',
  'Gift',
  'Camera',
  'Plane',
  'PawPrint',
  'Leaf',
  'Scale',
  'Donut',
];
